Added information about setup, gitignore and alias
pgdr/git-introduction pull request #1
Opened 2022-01-21 18:47 UTC by Dabendorf

Hei Pål,
After reading through that amazing tutorial I had the feeling that there is missing a little introduction into how to setup github, how to use .gitignore files and how to set aliases. I have therefore added one section with information about it.

You may want to change the position of the aliases since its a bit weird to talk about aliases before talking about the commands. I just did not find a better place for it.

Hilsen,
Lukas

2022-01-24 12:01 UTC, pgdr commented
Hi, Lukas! Thanks a lot for the contribution.  I would request a minor change; could you move the section _First time setup and configuration_ to after the section _Remotes_, and create a link in the section _The empty repository_ to that section?

Also, please write commit messages in _imperative mode_ instead of past tense, see [_How to Write a Git Commit Message_](https://chris.beams.io/posts/git-commit/).

2022-01-24 12:02 UTC, pgdr approved these changes

2022-01-24 12:02 UTC, pgdr requested changes
Please move section to end

2022-01-25 09:24 UTC, Dabendorf commented
Thank you for your reply. I moved the section, added a note in the empty repository section and changed the names of the commits.

2022-01-25 12:21 UTC, pgdr approved these changes

2022-01-25 12:21 UTC, merged